site_name: OpenAI Function call 
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant
plugins:
  - social
  - mkdocstrings:
      handlers:
        python:
          options:
            members_order: alphabetical
            allow_inspection: true
            show_bases: true
repo_url: https://github.com/jxnl/openai_function_call
site_url: https://openai-function-call.onrender.com/
markdown_extensions:
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - admonition
nav:
  - Quick Start: 'index.md'
  - API Reference:
      - 'OpenAISchema': 'openai_schema.md'
      - "MultiTask Schema": "multitask.md"
      - "Introduction: Pipeline API": "pipeline-example.md"
      - "Message Templates": "chat-completion.md"
  - Examples:
      - 'Table of contents': 'examples/index.md'
      - 'Segmented Search': 'examples/search.md'
      - 'One shot Query Planning': 'examples/planning-tasks.md'
      - 'Recursive Schemas': 'examples/recursive.md'
      - 'Exact Citations': 'examples/exact_citations.md'
      - 'Automated Dataframe Extraction': "examples/autodataframe.md"