name: Weekly Tests

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0" # Runs at 00:00 UTC every Sunday
  push:
    branches: [main]
    paths-ignore:
      - "**" # Ignore all paths to ensure it only triggers on schedule

jobs:
  weekly-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Cache UV virtualenv
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/uv
            ~/.uv
          key: ${{ runner.os }}-uv-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-uv-

      - name: Install UV
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Install dependencies
        run: |
          uv pip install -e ".[test-docs,anthropic]"
          uv pip install -r requirements-dev.txt

      - name: Run all tests
        run: pytest tests/
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
