name: Weekly Tests

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0" # Runs at 00:00 UTC every Sunday
  push:
    branches: [main]
    paths-ignore:
      - "**" # Ignore all paths to ensure it only triggers on schedule

jobs:
  weekly-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Cache UV virtualenv
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/uv
            ~/.uv
            .venv
          key: ${{ runner.os }}-uv-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-uv-

      - name: Install UV
        run: |
          if [ "$RUNNER_OS" == "Windows" ]; then
            curl -LsSf https://astral.sh/uv/install.sh | sh
            echo "$HOME/.local/bin" >> $GITHUB_PATH
          elif [ "$RUNNER_OS" == "macOS" ]; then
            curl -LsSf https://astral.sh/uv/install.sh | sh
            echo "$HOME/Library/Application Support/uv/bin" >> $GITHUB_PATH
          else
            curl -LsSf https://astral.sh/uv/install.sh | sh
            echo "$HOME/.local/bin" >> $GITHUB_PATH
          fi

      - name: Create and activate venv
        run: |
          python -m venv .venv
          if [ "$RUNNER_OS" == "Windows" ]; then
            . .venv/Scripts/activate
          else
            . .venv/bin/activate
          fi
        shell: bash

      - name: Install dependencies
        run: |
          which uv
          uv pip install -e ".[test-docs,anthropic,groq,cohere,mistralai,litellm,google-generativeai,vertexai,cerebras_cloud_sdk,fireworks-ai]" --system
          uv pip install -r requirements-dev.txt --system
        shell: bash

      - name: Run all tests
        run: pytest tests/
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
