name: Deploy MkDocs

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Calculate requirements hash
        id: req-hash
        run: echo "::set-output name=hash::$(sha256sum requirements-doc.txt | awk '{print $1}')"

      - name: Setup cache
        uses: actions/cache@v3
        with:
          key: mkdocs-material-${{ steps.req-hash.outputs.hash }}
          path: .cache
          restore-keys: |
            mkdocs-material-

      - name: Install Requirements
        run: |
          sudo apt-get update &&
          sudo apt-get install pngquant &&
          pip install -r requirements-doc.txt

        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Fetch documentation branch
        run: git fetch origin gh-pages --depth=1

      - name: Configure Git User
        run: |
          git config user.name "ci-bot"
          git config user.email "ci-bot@example.com"

      - name: Get current tag
        run: echo "version=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV

      - name: Build and deploy with mike
        run: mike deploy --update-aliases ${{ env.version }} latest --ignore-remote-status
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}