name: Pyright

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

env:
  WORKING_DIRECTORY: "."
  PYRIGHT_OUTPUT_FILENAME: "pyright.log"

jobs:
  Pyright:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ["3.10", "3.11"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache UV virtualenv
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/uv
            ~/.uv
            .venv
          key: ${{ runner.os }}-uv-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-uv-

      - name: Install UV
        run: |
          if [ "$RUNNER_OS" == "Windows" ]; then
            curl.exe -LsSf https://astral.sh/uv/install.ps1 | pwsh
          else
            curl -LsSf https://astral.sh/uv/install.sh | sh
          fi
          if [ "$RUNNER_OS" == "Windows" ]; then
            echo "$USERPROFILE/.cargo/bin" >> $GITHUB_PATH
          else
            echo "$HOME/.cargo/bin" >> $GITHUB_PATH
          fi
          uv --version
        shell: bash

      - name: Create and activate venv
        run: |
          python -m venv .venv
          if [ "$RUNNER_OS" == "Windows" ]; then
            source .venv/Scripts/activate
          else
            source .venv/bin/activate
          fi
          python --version  # Verify Python version
        shell: bash

      - name: Install dependencies
        run: |
          source .venv/bin/activate  # Ensure venv is activated
          python --version  # Verify Python version
          uv pip install -e ".[test-docs,anthropic,groq,cohere,mistralai,litellm,google-generativeai,vertexai,cerebras_cloud_sdk,fireworks-ai,writer]"
          uv pip install -r requirements-dev.txt
          uv pip install --upgrade "typing-extensions>=4.12.2" "requests>=2.32.3" "regex>=2024.11.6"
          uv pip list  # List installed packages for debugging
        shell: bash

      - uses: jakebailey/pyright-action@v2
        with:
          version: 1.1.373
