name: Pyright

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

env:
  WORKING_DIRECTORY: "."
  PYRIGHT_OUTPUT_FILENAME: "pyright.log"

jobs:
  Pyright:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ["3.9", "3.10", "3.11"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache UV virtualenv
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/uv
            ~/.uv
            .venv
          key: ${{ runner.os }}-uv-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-uv-

      - name: Install UV
        run: |
          if [ "$RUNNER_OS" == "Windows" ]; then
            curl -LsSf https://astral.sh/uv/install.sh | sh
            echo "$HOME/.local/bin" >> $GITHUB_PATH
          elif [ "$RUNNER_OS" == "macOS" ]; then
            curl -LsSf https://astral.sh/uv/install.sh | sh
            echo "$HOME/Library/Application Support/uv/bin" >> $GITHUB_PATH
          else
            curl -LsSf https://astral.sh/uv/install.sh | sh
            echo "$HOME/.local/bin" >> $GITHUB_PATH
          fi

      - name: Create and activate venv
        run: |
          python -m venv .venv
          if [ "$RUNNER_OS" == "Windows" ]; then
            . .venv/Scripts/activate
          else
            . .venv/bin/activate
          fi
        shell: bash

      - name: Install dependencies
        run: |
          which uv
          uv pip install -e ".[test-docs,anthropic,groq,cohere,mistralai,litellm,google-generativeai,vertexai,cerebras_cloud_sdk,fireworks-ai]" --system
          uv pip install -r requirements-dev.txt --system
        shell: bash

      - uses: jakebailey/pyright-action@v2
        with:
          version: 1.1.373
