name: Pyright

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

env:
  WORKING_DIRECTORY: "."
  PYRIGHT_OUTPUT_FILENAME: "pyright.log"

jobs:
  Pyright:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ["3.9", "3.10", "3.11"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache UV virtualenv
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/uv
            ~/.uv
            .venv
          key: ${{ runner.os }}-uv-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-uv-

      - name: Install UV
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Create and activate venv
        run: |
          python -m venv .venv
          source .venv/bin/activate

      - name: Install dependencies
        run: |
          uv pip install -e ".[test-docs,anthropic]"
          uv pip install -r requirements-dev.txt

      - uses: jakebailey/pyright-action@v2
        with:
          version: 1.1.373
