name: Ruff

on:
  push:
  pull_request:
    branches: [main]

env:
  WORKING_DIRECTORY: "."
  RUFF_OUTPUT_FILENAME: "ruff.log"
  CUSTOM_FLAGS: ""
  CUSTOM_PACKAGES: "instructor examples tests"

jobs:
  Ruff:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Environment setup
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install UV
        run: |
          if [ "$RUNNER_OS" == "Windows" ]; then
            curl -LsSf https://astral.sh/uv/install.sh | sh
            echo "$HOME/.local/bin" >> $GITHUB_PATH
          elif [ "$RUNNER_OS" == "macOS" ]; then
            curl -LsSf https://astral.sh/uv/install.sh | sh
            echo "$HOME/Library/Application Support/uv/bin" >> $GITHUB_PATH
          else
            curl -LsSf https://astral.sh/uv/install.sh | sh
            echo "$HOME/.local/bin" >> $GITHUB_PATH
          fi
      - name: Create and activate venv
        run: |
          python -m venv .venv
          if [ "$RUNNER_OS" == "Windows" ]; then
            . .venv/Scripts/activate
          else
            . .venv/bin/activate
          fi
        shell: bash
      - name: Install dev dependencies
        run: |
          uv pip install -r requirements.txt
          uv pip install -r requirements-doc.txt
        shell: bash
      - name: Run Continuous Integration Action
        uses: astral-sh/ruff-action@v1
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ruff-log
          path: ${{ env.WORKING_DIRECTORY }}/${{ env.RUFF_OUTPUT_FILENAME }}
